module dls2_interface
{
  module msg
  {
    struct StanceStatus
    {
      // header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      // data
      sequence<boolean> stance_status;
      // Estimated GRFs in base frame, flattened as [Fx, Fy, Fz] per limb id.
      sequence<double> estimated_grfs;
    };
  };
};
