#ifndef ROS2_INTERFACE_STD_MSGS_MSG_INT16_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_INT16_IDL_

module std_msgs {
  module msg {
    struct Int16 {
      int16 data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_INT16_IDL_
