#ifndef ROS2_INTERFACE_STD_MSGS_MSG_INT16MULTIARRAY_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_INT16MULTIARRAY_IDL_

#include "std_msgs/msg/MultiArrayLayout.idl"

module std_msgs {
  module msg {
    struct Int16MultiArray {
      std_msgs::msg::MultiArrayLayout layout;
      sequence<int16> data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_INT16MULTIARRAY_IDL_
