#ifndef ROS2_INTERFACE_STD_MSGS_MSG_STRING_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_STRING_IDL_

module std_msgs {
  module msg {
    struct String {
      string data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_STRING_IDL_
