#ifndef ROS2_INTERFACE_STD_MSGS_MSG_UINT8_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_UINT8_IDL_

module std_msgs {
  module msg {
    struct UInt8 {
      uint8 data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_UINT8_IDL_
