#ifndef ROS2_INTERFACE_STD_MSGS_MSG_UINT8MULTIARRAY_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_UINT8MULTIARRAY_IDL_

#include "std_msgs/msg/MultiArrayLayout.idl"

module std_msgs {
  module msg {
    struct UInt8MultiArray {
      std_msgs::msg::MultiArrayLayout layout;
      sequence<uint8> data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_UINT8MULTIARRAY_IDL_
