#ifndef ROS2_INTERFACE_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_IDL_
#define ROS2_INTERFACE_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_IDL_

module rcl_interfaces {
  module msg {
    struct SetParametersResult {
      boolean successful;
      string reason;
    };
  };
};

#endif // ROS2_INTERFACE_RCL_INTERFACES_MSG_SETPARAMETERSRESULT_IDL_
