#ifndef ROS2_INTERFACE_TYPE_DESCRIPTION_INTERFACES_MSG_FIELDTYPE_IDL_
#define ROS2_INTERFACE_TYPE_DESCRIPTION_INTERFACES_MSG_FIELDTYPE_IDL_

module type_description_interfaces {
  module msg {
    const uint8 FIELD_TYPE_NOT_SET = 0;
    const uint8 FIELD_TYPE_NESTED_TYPE = 1;
    const uint8 FIELD_TYPE_INT8 = 2;
    const uint8 FIELD_TYPE_UINT8 = 3;
    const uint8 FIELD_TYPE_INT16 = 4;
    const uint8 FIELD_TYPE_UINT16 = 5;
    const uint8 FIELD_TYPE_INT32 = 6;
    const uint8 FIELD_TYPE_UINT32 = 7;
    const uint8 FIELD_TYPE_INT64 = 8;
    const uint8 FIELD_TYPE_UINT64 = 9;
    const uint8 FIELD_TYPE_FLOAT = 10;
    const uint8 FIELD_TYPE_DOUBLE = 11;
    const uint8 FIELD_TYPE_LONG_DOUBLE = 12;
    const uint8 FIELD_TYPE_CHAR = 13;
    const uint8 FIELD_TYPE_WCHAR = 14;
    const uint8 FIELD_TYPE_BOOLEAN = 15;
    const uint8 FIELD_TYPE_BYTE = 16;
    const uint8 FIELD_TYPE_STRING = 17;
    const uint8 FIELD_TYPE_WSTRING = 18;
    const uint8 FIELD_TYPE_FIXED_STRING = 19;
    const uint8 FIELD_TYPE_FIXED_WSTRING = 20;
    const uint8 FIELD_TYPE_BOUNDED_STRING = 21;
    const uint8 FIELD_TYPE_BOUNDED_WSTRING = 22;
    const uint8 FIELD_TYPE_NESTED_TYPE_ARRAY = 49;
    const uint8 FIELD_TYPE_INT8_ARRAY = 50;
    const uint8 FIELD_TYPE_UINT8_ARRAY = 51;
    const uint8 FIELD_TYPE_INT16_ARRAY = 52;
    const uint8 FIELD_TYPE_UINT16_ARRAY = 53;
    const uint8 FIELD_TYPE_INT32_ARRAY = 54;
    const uint8 FIELD_TYPE_UINT32_ARRAY = 55;
    const uint8 FIELD_TYPE_INT64_ARRAY = 56;
    const uint8 FIELD_TYPE_UINT64_ARRAY = 57;
    const uint8 FIELD_TYPE_FLOAT_ARRAY = 58;
    const uint8 FIELD_TYPE_DOUBLE_ARRAY = 59;
    const uint8 FIELD_TYPE_LONG_DOUBLE_ARRAY = 60;
    const uint8 FIELD_TYPE_CHAR_ARRAY = 61;
    const uint8 FIELD_TYPE_WCHAR_ARRAY = 62;
    const uint8 FIELD_TYPE_BOOLEAN_ARRAY = 63;
    const uint8 FIELD_TYPE_BYTE_ARRAY = 64;
    const uint8 FIELD_TYPE_STRING_ARRAY = 65;
    const uint8 FIELD_TYPE_WSTRING_ARRAY = 66;
    const uint8 FIELD_TYPE_FIXED_STRING_ARRAY = 67;
    const uint8 FIELD_TYPE_FIXED_WSTRING_ARRAY = 68;
    const uint8 FIELD_TYPE_BOUNDED_STRING_ARRAY = 69;
    const uint8 FIELD_TYPE_BOUNDED_WSTRING_ARRAY = 70;
    const uint8 FIELD_TYPE_NESTED_TYPE_BOUNDED_SEQUENCE = 97;
    const uint8 FIELD_TYPE_INT8_BOUNDED_SEQUENCE = 98;
    const uint8 FIELD_TYPE_UINT8_BOUNDED_SEQUENCE = 99;
    const uint8 FIELD_TYPE_INT16_BOUNDED_SEQUENCE = 100;
    const uint8 FIELD_TYPE_UINT16_BOUNDED_SEQUENCE = 101;
    const uint8 FIELD_TYPE_INT32_BOUNDED_SEQUENCE = 102;
    const uint8 FIELD_TYPE_UINT32_BOUNDED_SEQUENCE = 103;
    const uint8 FIELD_TYPE_INT64_BOUNDED_SEQUENCE = 104;
    const uint8 FIELD_TYPE_UINT64_BOUNDED_SEQUENCE = 105;
    const uint8 FIELD_TYPE_FLOAT_BOUNDED_SEQUENCE = 106;
    const uint8 FIELD_TYPE_DOUBLE_BOUNDED_SEQUENCE = 107;
    const uint8 FIELD_TYPE_LONG_DOUBLE_BOUNDED_SEQUENCE = 108;
    const uint8 FIELD_TYPE_CHAR_BOUNDED_SEQUENCE = 109;
    const uint8 FIELD_TYPE_WCHAR_BOUNDED_SEQUENCE = 110;
    const uint8 FIELD_TYPE_BOOLEAN_BOUNDED_SEQUENCE = 111;
    const uint8 FIELD_TYPE_BYTE_BOUNDED_SEQUENCE = 112;
    const uint8 FIELD_TYPE_STRING_BOUNDED_SEQUENCE = 113;
    const uint8 FIELD_TYPE_WSTRING_BOUNDED_SEQUENCE = 114;
    const uint8 FIELD_TYPE_FIXED_STRING_BOUNDED_SEQUENCE = 115;
    const uint8 FIELD_TYPE_FIXED_WSTRING_BOUNDED_SEQUENCE = 116;
    const uint8 FIELD_TYPE_BOUNDED_STRING_BOUNDED_SEQUENCE = 117;
    const uint8 FIELD_TYPE_BOUNDED_WSTRING_BOUNDED_SEQUENCE = 118;
    const uint8 FIELD_TYPE_NESTED_TYPE_UNBOUNDED_SEQUENCE = 145;
    const uint8 FIELD_TYPE_INT8_UNBOUNDED_SEQUENCE = 146;
    const uint8 FIELD_TYPE_UINT8_UNBOUNDED_SEQUENCE = 147;
    const uint8 FIELD_TYPE_INT16_UNBOUNDED_SEQUENCE = 148;
    const uint8 FIELD_TYPE_UINT16_UNBOUNDED_SEQUENCE = 149;
    const uint8 FIELD_TYPE_INT32_UNBOUNDED_SEQUENCE = 150;
    const uint8 FIELD_TYPE_UINT32_UNBOUNDED_SEQUENCE = 151;
    const uint8 FIELD_TYPE_INT64_UNBOUNDED_SEQUENCE = 152;
    const uint8 FIELD_TYPE_UINT64_UNBOUNDED_SEQUENCE = 153;
    const uint8 FIELD_TYPE_FLOAT_UNBOUNDED_SEQUENCE = 154;
    const uint8 FIELD_TYPE_DOUBLE_UNBOUNDED_SEQUENCE = 155;
    const uint8 FIELD_TYPE_LONG_DOUBLE_UNBOUNDED_SEQUENCE = 156;
    const uint8 FIELD_TYPE_CHAR_UNBOUNDED_SEQUENCE = 157;
    const uint8 FIELD_TYPE_WCHAR_UNBOUNDED_SEQUENCE = 158;
    const uint8 FIELD_TYPE_BOOLEAN_UNBOUNDED_SEQUENCE = 159;
    const uint8 FIELD_TYPE_BYTE_UNBOUNDED_SEQUENCE = 160;
    const uint8 FIELD_TYPE_STRING_UNBOUNDED_SEQUENCE = 161;
    const uint8 FIELD_TYPE_WSTRING_UNBOUNDED_SEQUENCE = 162;
    const uint8 FIELD_TYPE_FIXED_STRING_UNBOUNDED_SEQUENCE = 163;
    const uint8 FIELD_TYPE_FIXED_WSTRING_UNBOUNDED_SEQUENCE = 164;
    const uint8 FIELD_TYPE_BOUNDED_STRING_UNBOUNDED_SEQUENCE = 165;
    const uint8 FIELD_TYPE_BOUNDED_WSTRING_UNBOUNDED_SEQUENCE = 166;

    struct FieldType {
      uint8 type_id;
      uint64 capacity;
      uint64 string_capacity;
      string<255> nested_type_name;
    };
  };
};

#endif // ROS2_INTERFACE_TYPE_DESCRIPTION_INTERFACES_MSG_FIELDTYPE_IDL_
