#ifndef ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_INTERACTIVEMARKERPOSE_IDL_
#define ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_INTERACTIVEMARKERPOSE_IDL_

#include "geometry_msgs/msg/Pose.idl"
#include "std_msgs/msg/Header.idl"

module visualization_msgs {
  module msg {
    struct InteractiveMarkerPose {
      std_msgs::msg::Header header;
      geometry_msgs::msg::Pose pose;
      string name;
    };
  };
};

#endif // ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_INTERACTIVEMARKERPOSE_IDL_
