#include "base_state_light.idl"
#include "header.idl"

module dls2_interface {
    module msg {
        struct BaseReference 
        {    
            DLSHeader header;

            BaseStateLight target_state;
        };
    };
};