#include "BaseStateLight.idl"
#include "DLSHeader.idl"

module dls2_interface {
    module msg {
        struct BaseReference 
        {    
            DLSHeader header;

            BaseStateLight target_state;
        };
    };
};