#include "Pose.idl"
#include "Screw.idl"

module dls2_interface {
  	module msg {
		struct BaseStateLight
		{
			dls2_interface::msg::Pose pose;
			dls2_interface::msg::Screw velocity;
			dls2_interface::msg::Screw acceleration;
		};
	};
};