#include "base_state_light.idl"

module dls2_interface {
    module msg {
        struct BaseReference {
            // Header
            unsigned long sequence_id;
            double timestamp;

            BaseStateLight target_state;
        };
    };
};