#include "dls_annotation.idl"
#include "pose.idl"
#include "screw.idl"

@Robot
struct BaseState
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	string robot_name;

	// Base Pose
	Pose pose;

	// Base velocity
	Screw velocity;

	// Base acceleration
	Screw acceleration;

	// Stance status
	@LimbDataMap sequence<boolean> stance_status;
};
