#include "header.idl"

module dls2_interface {
	module msg {
		struct BatteryStatus
		{
            DLSHeader header;
			string frame_id;

			double temperature;
			double current;
			double voltage;
			double state_of_charge;
		};
	};
};