module dls2_interface
{
  module msg
  {
    enum Button
    {
      NONE,
      CROSS_L_UD,
      CROSS_L_LR,
      CROSS_R_UD,
      CROSS_R_LR,
      STICK_L_UD,
      STICK_L_LR,
      STICK_R_UD,
      STICK_R_LR,
      BUTTON_A,
      BUTTON_B,
      BUTTON_X,
      BUTTON_Y,
      BUTTON_PLUS,
      BUTTON_MINUS,
      BUTTON_START,
      BUTTON_BACK,
      BUMPER_LT,
      BUMPER_LB,
      BUMPER_L1,
      BUMPER_L2,
      BUMPER_L3,
      BUMPER_L4,
      BUMPER_RT,
      BUMPER_RB,
      BUMPER_R1,
      BUMPER_R2,
      BUMPER_R3,
      BUMPER_R4
    };

    struct ButtonEvent
    {
      // head
      unsigned long sequence_id;
      double timestamp;

      // content
      Button button;
      double value;
    };
  };
};
