struct CommandCall
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	string owner;
	string command_name;
	string docstring;

	string args;
	string ret;
	boolean status; // true means success
};
