#include "dls_annotation.idl"

@Robot
struct ControlSignal
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	@JointState	sequence<double> torques;
	unsigned long long signal_reconstruction_method;
};
