#include "Pose.idl"
#include "Screw.idl"

module dls2_interface
{
  module msg
  {
    struct ControllerCommand
    {
      // Header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      double robot_height;
      double step_frequency;
      double duty_factor;
      sequence<double> step_height;

      dls2_interface::msg::Pose base_pose_HF;

      dls2_interface::msg::Screw base_velocity_HF;
    };
  };
};
