module dls2_interface {
  	module msg {
			struct ControlSignal
			{
				// Header
				string frame_id;
				unsigned long sequence_id;
				double timestamp;
				sequence<double> torques;
				unsigned long long signal_reconstruction_method;
			};
	};
};