#include "dls_annotation.idl"
#include "pose.idl"
#include "screw.idl"

@Robot
struct ControllerCommand
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	double robot_height;
    double step_frequency;
    double duty_factor;
    @LimbDataMap sequence<double> step_height;

	Pose base_pose_HF;

	Screw base_velocity_HF;
};