module dls2_interface {
	module msg {
		struct CSBasicCommand{
			
			// Header
			unsigned long sequence_id;
			double timestamp;

			uint32 autonomy_level;
			uint32 locomotion_strategy;
			uint32 control_strategy;

			boolean enable;
		};
	};
};
