module dls2_interface {
  module msg {
	struct DesiredTorques
	{
		// Header
		string frame_id;
		unsigned long sequence_id;
		double timestamp;

		//data
		sequence<double> desired_torques;
	};
  };
};
