#include "process_status.idl"
#include "reference.idl"
#include "robot_state.idl"
#include "battery_status.idl"

module dls2_interface {
	module msg {
		struct DLSStatus
		{
			// Header
			string frame_id;
			unsigned long sequence_id;
			double timestamp;

			sequence<ProcessStatusLight> processes; 
			Reference reference;
			RobotState robot_state;
			BatteryStatus battery_status;
		};
	};
};