#ifndef DLS2_INTERFACE_MSG_HEADER_IDL_
#define DLS2_INTERFACE_MSG_HEADER_IDL_ 

module dls2_interface
{
  module msg
  {
    struct DlsHeader
    {
      string frame_id;
      unsigned long sequence_id;
      unsigned long long timestamp;
    };
  };
};

#endif // DLS2_INTERFACE_MSG_HEADER_IDL_