#include "BlindStateLight.idl"
#include "BaseStateLight.idl"
#include "WrenchLight.idl"
#include "BatteryStatusLight.idl"
#include "FrictionConeList.idl"
#include "Vec3.idl"

module dls2_interface {
	module msg {
		struct DLSRobotStateLight
		{
			BlindStateLight blind_state;
			BaseStateLight base_state;

			WrenchLight base_wrench;

			sequence<Vec3> feet_forces;
			FrictionConeList friction_cones;

			uint32 locomotion_strategy;

			BatteryStatusLight battery_status;
		};
	};
};