#include "ProcessStatusLight.idl"
#include "ReferenceLight.idl"
#include "DlsRobotStateLight.idl"
#include "DlsHeader.idl"

module dls2_interface {
	module msg {
		struct DlsStatus
		{
			dls2_interface::msg::DlsHeader header;

			sequence<dls2_interface::msg::ProcessStatusLight> processes; 
			dls2_interface::msg::ReferenceLight reference;
			dls2_interface::msg::DlsRobotStateLight robot_state;
		};
	};
};