#include "ProcessStatusLight.idl"
#include "ReferenceLight.idl"
#include "DLSRobotStateLight.idl"
#include "DLSHeader.idl"

module dls2_interface {
	module msg {
		struct DLSStatus
		{
			DLSHeader header;
			string frame_id;

			sequence<ProcessStatusLight> processes; 
			ReferenceLight reference;
			DLSRobotStateLight robot_state;
		};
	};
};