module dls2_interface
{
  module msg
  {
    struct Double
    {
      // header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      // data
      double value;
    };
  };
};
