#include "Vec3.idl"
#include "header.idl"

module dls2_interface {
    module msg {
        struct FeetReference 
        {
            DLSHeader header;

            sequence<uint32> feet_ids;
	        sequence<Vec3> feet_position;
        };
    };
};