#include "Vec3.idl"

module dls2_interface {
    module msg {
        struct FeetReference {
            // Header
            unsigned long sequence_id;
            double timestamp;

            sequence<uint32> feet_ids;
	        sequence<Vec3> feet_position;
        };
    };
};