module dls2_interface {
	module msg {
		struct JointStates
			{
				// Header
				string frame_id;
				unsigned long sequence_id;
				double timestamp;

				// Vector3d
				sequence<double> q;
				sequence<double> qd;
				sequence<double> qdd;
			};
		};
};
