#include "header.idl"

module dls2_interface {
	module msg {
		struct JointStates
			{
				DLSHeader header;
				string frame_id;

				// Vector3d
				sequence<double> q;
				sequence<double> qd;
				sequence<double> qdd;
			};
		};
};
