#include "dls_annotation.idl"

@Robot @Eigen
struct LegsPose
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	@LimbDataMap_EigenVector3 sequence<double> linear_velocity;
	@LimbDataMap_EigenVector3 sequence<double> angular_velocity;

	double base_velocity[3];

	@LimbDataMap sequence<boolean> stance_status;
};
