module dls2_interface
{
  module msg
  {
    enum TeleOpMode
    {
      NONE,
      NAVIGATION,
      STATIC,
      LOW
    };

    struct OperationalMode
    {
      // Header
      unsigned long sequence_id;
      double timestamp;

      TeleOpMode teleoperation_mode;
      unsigned short arm_control_mode;
      unsigned short arm_deployment;
    };
  };
};
