#include "Header.idl"
#include "PoseRos.idl"

module geometry_msgs {
  module msg {
    struct PoseArray {
      std_msgs::msg::Header header;
      sequence<geometry_msgs::msg::Pose> poses;
    };
  };
};
