#include "position2D.idl"
#include "header.idl"

module dls2_interface {
    module msg {
        struct ReferencePath 
        {
   			DLSHeader header;
            string frame_id;

            sequence<Position2D> path;
        };
    };
};