#include "JointStatesLight.idl"
#include "Pose.idl"
#include "screw.idl"
#include "Vec3.idl"

module dls2_interface {
	module msg {
		struct ReferenceLight
		{
			sequence<double> joint_torques;
			JointStatesLight joints_state;
			
			sequence<Vec3> feet_forces;

			Pose base_pose;
			Screw base_velocity;

			sequence<Pose> traj_poses;
			sequence<Screw> traj_screws;
		};
	};
};