#include "pose.idl"
#include "screw.idl"

module dls2_interface {
	module msg {
		struct Reference
		{
			// Header
			string frame_id;
			unsigned long sequence_id;
			double timestamp;

			sequence<double> desired_torques;

			sequence<double> joints_position;
			sequence<double> joints_velocity;
			sequence<double> joints_acceleration;
			
			Pose base_pose;
			Screw base_velocity;

			sequence<Pose> traj_poses;
			sequence<Screw> traj_screws;
		};
	};
};