#include "Position2D.idl".idl"
#include "DLSHeader.idl"

module dls2_interface {
    module msg {
        struct ReferencePath 
        {
   			DLSHeader header;
            string frame_id;

            sequence<Position2D> path;
        };
    };
};