#include "blind_state.idl"
#include "base_state.idl"

module dls2_interface {
	module msg {
		struct RobotState
		{
			// Header
			string frame_id;
			unsigned long sequence_id;
			double timestamp;

			BlindState blind_state;
			BaseState base_state;
			uint32 locomotion_strategy;
		};
	};
};