module dls2_interface {
	module msg {
	struct SensorFusion
	{
		// Header
		string frame_id;
		unsigned long sequence_id;
		double timestamp;
	
	    double position[3];
	    double linear_velocity[3];
	};
	};
};
