#include "dls_annotation.idl"

@Robot
struct SlipFlag
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	// Robot
	string robot_name;
	
	// Slip detection
	@LimbDataMap sequence<double> slip_flag;
};