#include "dls_annotation.idl"

@Robot
struct StanceStatus
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	// Stance status
	@LimbDataMap sequence<boolean> stance_status;
};