struct StateMachineMonitor
{       
       // Unique name
       string app_name;

       // Current State
       string state;

       // Define if the activity of the state is running in realtime
       boolean realtime;
};