#include "zone.idl"
#include "header.idl"

module dls2_interface {
    module msg {
        struct StayOutZones 
        {
            DLSHeader header;
            string frame_id;

            sequence<Zone> zones;
        };
    };
};