#include "position2D.idl"
#include "header.idl"

module dls2_interface {
    module msg {
        struct TargetPosition 
        {
            DLSHeader header;
            string frame_id;

            Position2D target_position;
        };
    };
};