#include "Position2D.idl".idl"
#include "DLSHeader.idl"

module dls2_interface {
    module msg {
        struct TargetPosition 
        {
            DLSHeader header;
            string frame_id;

            Position2D target_position;
        };
    };
};