#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TRANSFORM_STAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TRANSFORM_STAMPED_IDL_

#include "Header.idl"
#include "Transform.idl"

module geometry_msgs {
  module msg {
    struct TransformStamped {
      std_msgs::msg::Header header;
      string child_frame_id;
      geometry_msgs::msg::Transform transform;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TRANSFORM_STAMPED_IDL_
