#include "dls_annotation.idl"

@Robot
struct TrunkControllerDebug
{
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	// Actual feet forces
	@LimbDataMap_EigenVector3 sequence<double> feet_forces;
	@LimbDataMap_EigenVector3 sequence<double> desired_forces;

	double desired_wrench[6];

	@LimbDataMap sequence<double>  friction_coefficients;

	@JointState sequence<double> gravity_term;
	@JointState sequence<double>  coriolis_centrifugal_terms;
};
