#ifndef ROS2_INTERFACE_STATISTICS_MSGS_MSG_STATISTICDATATYPE_IDL_
#define ROS2_INTERFACE_STATISTICS_MSGS_MSG_STATISTICDATATYPE_IDL_

module statistics_msgs {
  module msg {
    const uint8 STATISTICS_DATA_TYPE_UNINITIALIZED = 0;
    const uint8 STATISTICS_DATA_TYPE_AVERAGE = 1;
    const uint8 STATISTICS_DATA_TYPE_MINIMUM = 2;
    const uint8 STATISTICS_DATA_TYPE_MAXIMUM = 3;
    const uint8 STATISTICS_DATA_TYPE_STDDEV = 4;
    const uint8 STATISTICS_DATA_TYPE_SAMPLE_COUNT = 5;

    struct StatisticDataType {
    };
  };
};

#endif // ROS2_INTERFACE_STATISTICS_MSGS_MSG_STATISTICDATATYPE_IDL_
