#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINTSTAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINTSTAMPED_IDL_

#include "geometry_msgs/msg/Point.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct PointStamped {
      std_msgs::msg::Header header;
      geometry_msgs::msg::Point point;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINTSTAMPED_IDL_
