#ifndef ROS2_INTERFACE_STD_MSGS_MSG_FLOAT64_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_FLOAT64_IDL_

module std_msgs {
  module msg {
    struct Float64 {
      double data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_FLOAT64_IDL_
