#ifndef ROS2_INTERFACE_STD_MSGS_MSG_UINT64_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_UINT64_IDL_

module std_msgs {
  module msg {
    struct UInt64 {
      uint64 data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_UINT64_IDL_
