#ifndef ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MESHFILE_IDL_
#define ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MESHFILE_IDL_

module visualization_msgs {
  module msg {
    struct MeshFile {
      string filename;
      sequence<uint8> data;
    };
  };
};

#endif // ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_MESHFILE_IDL_
