#ifndef ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_UVCOORDINATE_IDL_
#define ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_UVCOORDINATE_IDL_

module visualization_msgs {
  module msg {
    struct UVCoordinate {
      float u;
      float v;
    };
  };
};

#endif // ROS2_INTERFACE_VISUALIZATION_MSGS_MSG_UVCOORDINATE_IDL_
