#ifndef ROS2_INTERFACE_ROSGRAPH_MSGS_MSG_SERVICE_IDL_
#define ROS2_INTERFACE_ROSGRAPH_MSGS_MSG_SERVICE_IDL_

#include "rosgraph_msgs/msg/InterfaceType.idl"
#include "rosgraph_msgs/msg/QoSProfile.idl"

module rosgraph_msgs {
  module msg {
    struct Service {
      string name;
      rosgraph_msgs::msg::InterfaceType request_type;
      rosgraph_msgs::msg::QoSProfile request_qos;
      rosgraph_msgs::msg::InterfaceType response_type;
      rosgraph_msgs::msg::QoSProfile response_qos;
    };
  };
};

#endif // ROS2_INTERFACE_ROSGRAPH_MSGS_MSG_SERVICE_IDL_
