#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POLYGONINSTANCESTAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POLYGONINSTANCESTAMPED_IDL_

#include "geometry_msgs/msg/PolygonInstance.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct PolygonInstanceStamped {
      std_msgs::msg::Header header;
      geometry_msgs::msg::PolygonInstance polygon;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POLYGONINSTANCESTAMPED_IDL_
