#ifndef ROS2_INTERFACE_SENSOR_MSGS_MSG_POINTCLOUD_IDL_
#define ROS2_INTERFACE_SENSOR_MSGS_MSG_POINTCLOUD_IDL_

#include "geometry_msgs/msg/Point32.idl"
#include "sensor_msgs/msg/ChannelFloat32.idl"
#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    struct PointCloud {
      std_msgs::msg::Header header;
      sequence<geometry_msgs::msg::Point32> points;
      sequence<sensor_msgs::msg::ChannelFloat32> channels;
    };
  };
};

#endif // ROS2_INTERFACE_SENSOR_MSGS_MSG_POINTCLOUD_IDL_
