#ifndef ROS2_INTERFACE_SENSOR_MSGS_MSG_CAMERAINFO_IDL_
#define ROS2_INTERFACE_SENSOR_MSGS_MSG_CAMERAINFO_IDL_

#include "sensor_msgs/msg/RegionOfInterest.idl"
#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    struct CameraInfo {
      std_msgs::msg::Header header;
      uint32 height;
      uint32 width;
      string distortion_model;
      sequence<double> d;
      double k[9];
      double r[9];
      double p[12];
      uint32 binning_x;
      uint32 binning_y;
      sensor_msgs::msg::RegionOfInterest roi;
    };
  };
};

#endif // ROS2_INTERFACE_SENSOR_MSGS_MSG_CAMERAINFO_IDL_
