#ifndef ROS2_INTERFACE_SENSOR_MSGS_MSG_FLUIDPRESSURE_IDL_
#define ROS2_INTERFACE_SENSOR_MSGS_MSG_FLUIDPRESSURE_IDL_

#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    struct FluidPressure {
      std_msgs::msg::Header header;
      double fluid_pressure;
      double variance;
    };
  };
};

#endif // ROS2_INTERFACE_SENSOR_MSGS_MSG_FLUIDPRESSURE_IDL_
