#ifndef ROS2_INTERFACE_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_IDL_
#define ROS2_INTERFACE_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_IDL_

#include "sensor_msgs/msg/LaserEcho.idl"
#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    struct MultiEchoLaserScan {
      std_msgs::msg::Header header;
      float angle_min;
      float angle_max;
      float angle_increment;
      float time_increment;
      float scan_time;
      float range_min;
      float range_max;
      sequence<sensor_msgs::msg::LaserEcho> ranges;
      sequence<sensor_msgs::msg::LaserEcho> intensities;
    };
  };
};

#endif // ROS2_INTERFACE_SENSOR_MSGS_MSG_MULTIECHOLASERSCAN_IDL_
