#ifndef ROS2_INTERFACE_SENSOR_MSGS_MSG_TEMPERATURE_IDL_
#define ROS2_INTERFACE_SENSOR_MSGS_MSG_TEMPERATURE_IDL_

#include "std_msgs/msg/Header.idl"

module sensor_msgs {
  module msg {
    struct Temperature {
      std_msgs::msg::Header header;
      double temperature;
      double variance;
    };
  };
};

#endif // ROS2_INTERFACE_SENSOR_MSGS_MSG_TEMPERATURE_IDL_
