#ifndef ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_STATE_IDL_
#define ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_STATE_IDL_

module lifecycle_msgs {
  module msg {
    const uint8 PRIMARY_STATE_UNKNOWN = 0;
    const uint8 PRIMARY_STATE_UNCONFIGURED = 1;
    const uint8 PRIMARY_STATE_INACTIVE = 2;
    const uint8 PRIMARY_STATE_ACTIVE = 3;
    const uint8 PRIMARY_STATE_FINALIZED = 4;
    const uint8 TRANSITION_STATE_CONFIGURING = 10;
    const uint8 TRANSITION_STATE_CLEANINGUP = 11;
    const uint8 TRANSITION_STATE_SHUTTINGDOWN = 12;
    const uint8 TRANSITION_STATE_ACTIVATING = 13;
    const uint8 TRANSITION_STATE_DEACTIVATING = 14;
    const uint8 TRANSITION_STATE_ERRORPROCESSING = 15;

    struct State {
      uint8 id;
      string label;
    };
  };
};

#endif // ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_STATE_IDL_
