#ifndef ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_TRANSITIONDESCRIPTION_IDL_
#define ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_TRANSITIONDESCRIPTION_IDL_

#include "lifecycle_msgs/msg/State.idl"
#include "lifecycle_msgs/msg/Transition.idl"

module lifecycle_msgs {
  module msg {
    struct TransitionDescription {
      lifecycle_msgs::msg::Transition transition;
      lifecycle_msgs::msg::State start_state;
      lifecycle_msgs::msg::State goal_state;
    };
  };
};

#endif // ROS2_INTERFACE_LIFECYCLE_MSGS_MSG_TRANSITIONDESCRIPTION_IDL_
