#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINT_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINT_IDL_

module geometry_msgs {
  module msg {
    struct Point {
      double x;
      double y;
      double z;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POINT_IDL_
