#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSE_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSE_IDL_

#include "geometry_msgs/msg/Point.idl"
#include "geometry_msgs/msg/Quaternion.idl"

module geometry_msgs {
  module msg {
    struct Pose {
      geometry_msgs::msg::Point position;
      geometry_msgs::msg::Quaternion orientation;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSE_IDL_
