#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSEARRAY_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSEARRAY_IDL_

#include "geometry_msgs/msg/Pose.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct PoseArray {
      std_msgs::msg::Header header;
      sequence<geometry_msgs::msg::Pose> poses;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_POSEARRAY_IDL_
