#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TWISTSTAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TWISTSTAMPED_IDL_

#include "geometry_msgs/msg/Twist.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct TwistStamped {
      std_msgs::msg::Header header;
      geometry_msgs::msg::Twist twist;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_TWISTSTAMPED_IDL_
