#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_IDL_

#include "geometry_msgs/msg/Twist.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct VelocityStamped {
      std_msgs::msg::Header header;
      string body_frame_id;
      string reference_frame_id;
      geometry_msgs::msg::Twist velocity;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_VELOCITYSTAMPED_IDL_
