#ifndef ROS2_INTERFACE_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_IDL_
#define ROS2_INTERFACE_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_IDL_

#include "geometry_msgs/msg/Wrench.idl"
#include "std_msgs/msg/Header.idl"

module geometry_msgs {
  module msg {
    struct WrenchStamped {
      std_msgs::msg::Header header;
      geometry_msgs::msg::Wrench wrench;
    };
  };
};

#endif // ROS2_INTERFACE_GEOMETRY_MSGS_MSG_WRENCHSTAMPED_IDL_
