module dls2_interface
{
  module msg
  {
    struct NavigationReference
    {
      // header
      unsigned long sequence_id;
      double timestamp;

      double velocity[3]; // x, y, yaw
      double robot_height;
      boolean start;
    };
  };
};
