// EDIT#1/7 use it when PlotJuggler plugin for FastDDS supports the inclusion of custom messages
//#include "position.idl"
module dls2_interface
{
  module msg
  {
    struct Vicon
    {
      // header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      // robot pose
      double robot_position[3];
      double robot_orientation[4];

      // marker positions
      // EDIT#2/7 use it when PlotJuggler plugin for FastDDS supports the inclusion of custom messages
      // sequence<Position> markers_positions;
      // sequence<double> markers_positions;
      double markers_positions[21]; // 7 markers * 3 (x,y,z)
    };
  };
};
