#ifndef ROS2_INTERFACE_TF2_MSGS_MSG_TFMESSAGE_IDL_
#define ROS2_INTERFACE_TF2_MSGS_MSG_TFMESSAGE_IDL_

#include "geometry_msgs/msg/TransformStamped.idl"

module tf2_msgs {
  module msg {
    struct TFMessage {
      sequence<geometry_msgs::msg::TransformStamped> transforms;
    };
  };
};

#endif // ROS2_INTERFACE_TF2_MSGS_MSG_TFMESSAGE_IDL_
