#ifndef ROS2_INTERFACE_STATISTICS_MSGS_MSG_METRICSMESSAGE_IDL_
#define ROS2_INTERFACE_STATISTICS_MSGS_MSG_METRICSMESSAGE_IDL_

#include "builtin_interfaces/msg/Time.idl"
#include "statistics_msgs/msg/StatisticDataPoint.idl"

module statistics_msgs {
  module msg {
    struct MetricsMessage {
      string measurement_source_name;
      string metrics_source;
      string unit;
      builtin_interfaces::msg::Time window_start;
      builtin_interfaces::msg::Time window_stop;
      sequence<statistics_msgs::msg::StatisticDataPoint> statistics;
    };
  };
};

#endif // ROS2_INTERFACE_STATISTICS_MSGS_MSG_METRICSMESSAGE_IDL_
