#ifndef ROS2_INTERFACE_STD_MSGS_MSG_FLOAT32_IDL_
#define ROS2_INTERFACE_STD_MSGS_MSG_FLOAT32_IDL_

module std_msgs {
  module msg {
    struct Float32 {
      float data;
    };
  };
};

#endif // ROS2_INTERFACE_STD_MSGS_MSG_FLOAT32_IDL_
